apiVersion: "nuclio.io/v1"
kind: Function
metadata:
  name: consumehumidity
  namespace: nuclio
spec:
  handler: "main:handler"
  description: "Function called when a new message is arrived on the iot/sensors/humidity queue."
  runtime: nodejs
  image: "nuclio/processor-consumehumidity:latest"
  minReplicas: 1
  maxReplicas: 1
  targetCPU: 75
  triggers:
    myMqttTrigger:
      kind: "mqtt"
      url: "guest:guest@192.168.1.4:1883"
      attributes:
          subscriptions:
          - topic: iot/sensors/humidity
            qos: 0
  build:
    functionSourceCode: dmFyIG1xdHQgPSByZXF1aXJlKCJtcXR0Iik7CnZhciB1cmwgPSByZXF1aXJlKCJ1cmwiKTsKCnZhciBtcXR0X3VybCA9IHVybC5wYXJzZSgKICAgIHByb2Nlc3MuZW52LkNMT1VEQU1RUF9NUVRUX1VSTCB8fAogICAgIm1xdHQ6Ly9ndWVzdDpndWVzdEAxOTIuMTY4LjEuNDoxODgzIgopOwp2YXIgYXV0aCA9IChtcXR0X3VybC5hdXRoIHx8ICI6Iikuc3BsaXQoIjoiKTsKdmFyIHVybCA9ICJtcXR0Oi8vIiArIG1xdHRfdXJsLmhvc3Q7CnZhciBvcHRpb25zID0gewogIHBvcnQ6IG1xdHRfdXJsLnBvcnQsCiAgY2xpZW50SWQ6ICJtcXR0anNfIiArIE1hdGgucmFuZG9tKCkudG9TdHJpbmcoMTYpLnN1YnN0cigyLCA4KSwKICB1c2VybmFtZTogYXV0aFswXSwKICBwYXNzd29yZDogYXV0aFsxXSwKfTsKCmZ1bmN0aW9uIGJpbjJzdHJpbmcoYXJyYXkpIHsKICB2YXIgcmVzdWx0ID0gIiI7CiAgZm9yICh2YXIgaSA9IDA7IGkgPCBhcnJheS5sZW5ndGg7ICsraSkgewogICAgcmVzdWx0ICs9IFN0cmluZy5mcm9tQ2hhckNvZGUoYXJyYXlbaV0pOwogIH0KICByZXR1cm4gcmVzdWx0Owp9CgpleHBvcnRzLmhhbmRsZXIgPSBmdW5jdGlvbiAoY29udGV4dCwgZXZlbnQpIHsKICB2YXIgX2V2ZW50ID0gSlNPTi5wYXJzZShKU09OLnN0cmluZ2lmeShldmVudCkpOwogIHZhciBfZGF0YSA9IGJpbjJzdHJpbmcoX2V2ZW50LmJvZHkuZGF0YSk7CiAgLy92YXIgaHVtaWRpdHkgPSBwYXJzZUludChfZGF0YSk7CiAgdmFyIGNsaWVudCA9IG1xdHQuY29ubmVjdCh1cmwsIG9wdGlvbnMpOwoKICBjbGllbnQub24oJ2Nvbm5lY3QnLCBmdW5jdGlvbigpIHsKICAgIGNsaWVudC5wdWJsaXNoKCdpb3QvbG9ncycsIF9kYXRhLCBmdW5jdGlvbigpIHsKICAgICAgaWYgKHBhcnNlSW50KF9kYXRhKSA+PSA1MCkgewogICAgICAgIGNsaWVudC5wdWJsaXNoKCdpb3QvYWxlcnRzJywgX2RhdGEsIGZ1bmN0aW9uKCkgewogICAgICAgICAgICAgICAgICAgIGNsaWVudC5lbmQoKTsgCiAgICAgICAgICAgICAgICAgICAgY29udGV4dC5jYWxsYmFjaygnTVFUVC1hbGVydHMgTWVzc2FnZSBTZW50Jyk7CiAgICAgICAgICAgICAgICB9ICk7CiAgICAgIH0gaWYgKHBhcnNlSW50KF9kYXRhKSA8PSAzMCkgewogICAgICAgIGNsaWVudC5wdWJsaXNoKCdpb3QvbG9ncycsICJEZWh1bWlkaWZpZXIgZGVhY3RpdmF0ZWQgISEiLCBmdW5jdGlvbigpIHsKICAgICAgICAgICAgICAgICAgICBjbGllbnQuZW5kKCk7IAogICAgICAgICAgICAgICAgICAgIGNvbnRleHQuY2FsbGJhY2soJ01RVFQtbG9ncyBNZXNzYWdlIFNlbnQnKTsKICAgICAgICAgICAgICAgIH0gKTsKICAgICAgfSBlbHNlIHsKICAgICAgICAgICAgY2xpZW50LmVuZCgpOyAKICAgICAgICAgICAgY29udGV4dC5jYWxsYmFjaygnTVFUVC1sb2dzIE1lc3NhZ2UgU2VudCcpOwogICAgICAgICAgfQogICAgICB9KTsgICAgICAgICAgCiAgICB9KTsgCn07
    commands:
      - 'npm install mqtt'
    codeEntryType: sourceCode
  platform: {}
