apiVersion: "nuclio.io/v1"
kind: Function
metadata:
  name: sendhumidity
  namespace: nuclio
spec:
  handler: "main:handler"
  description: "Function to generate an event on the MQTT queue sending an humidity value."
  runtime: nodejs
  image: "nuclio/processor-sendhumidity:latest"
  minReplicas: 1
  maxReplicas: 1
  targetCPU: 75
  triggers:
    myCronTrigger:
      kind: cron
      attributes:
        interval: 5s
  build:
    functionSourceCode: dmFyIG1xdHQgPSByZXF1aXJlKCJtcXR0Iik7CnZhciB1cmwgPSByZXF1aXJlKCJ1cmwiKTsKdmFyIHJlZGlzID0gcmVxdWlyZSgicmVkaXMiKTsKCnZhciBtcXR0X3VybCA9IHVybC5wYXJzZSgKICAgIHByb2Nlc3MuZW52LkNMT1VEQU1RUF9NUVRUX1VSTCB8fAogICAgIm1xdHQ6Ly9ndWVzdDpndWVzdEAxOTIuMTY4LjEuNDoxODgzIgopOwp2YXIgYXV0aCA9IChtcXR0X3VybC5hdXRoIHx8ICI6Iikuc3BsaXQoIjoiKTsKdmFyIHVybCA9ICJtcXR0Oi8vIiArIG1xdHRfdXJsLmhvc3Q7CnZhciBvcHRpb25zID0gewogIHBvcnQ6IG1xdHRfdXJsLnBvcnQsCiAgY2xpZW50SWQ6ICJtcXR0anNfIiArIE1hdGgucmFuZG9tKCkudG9TdHJpbmcoMTYpLnN1YnN0cigyLCA4KSwKICB1c2VybmFtZTogYXV0aFswXSwKICBwYXNzd29yZDogYXV0aFsxXSwKfTsKCmV4cG9ydHMuaGFuZGxlciA9IGZ1bmN0aW9uIChjb250ZXh0LCBldmVudCkgewogICAgdmFyIGNsaWVudCA9IG1xdHQuY29ubmVjdCh1cmwsIG9wdGlvbnMpOwogICAgY29uc3QgY2xpZW50UmVkaXMgPSByZWRpcy5jcmVhdGVDbGllbnQoe2hvc3Q6ICIxOTIuMTY4LjEuNCJ9KTsKICAKICAgIGNsaWVudC5vbigiY29ubmVjdCIsIGZ1bmN0aW9uICgpIHsKICAgICAgY2xpZW50UmVkaXMuZ2V0KCJodW1pZGl0eSIsIGZ1bmN0aW9uKGVycm9yLCBodW1pZGl0eSkgewogICAgICAgICAgaWYgKGVycm9yKSB0aHJvdyBlcnJvcgogICAgICAgICAgaWYgKGh1bWlkaXR5ID09IG51bGwpIHsKICAgICAgICAgICAgaHVtaWRpdHkgPSAiMzIiOwogICAgICAgICAgICBjbGllbnRSZWRpcy5zZXQoImh1bWlkaXR5IiwgaHVtaWRpdHkpOwogICAgICAgICAgICBjbGllbnRSZWRpcy5zZXQoIm9yZGVyIiwgImFzY2VuZGluZyIpOwogICAgICAgICAgICBjbGllbnQucHVibGlzaCgiaW90L3NlbnNvcnMvaHVtaWRpdHkiLCBodW1pZGl0eSwgZnVuY3Rpb24gKCkgewogICAgICAgICAgICAgIGNsaWVudC5lbmQoKTsKICAgICAgICAgICAgICBjb250ZXh0LmNhbGxiYWNrKCJTZW50ICIgKyBodW1pZGl0eSk7CiAgICAgICAgICAgIH0pOwogICAgICAgICAgfSBlbHNlIHsKICAgICAgICAgICAgICBjbGllbnRSZWRpcy5nZXQoIm9yZGVyIiwgZnVuY3Rpb24oZXJyLCBvcmRlcikgewogICAgICAgICAgICAgICAgICBpZiAoZXJyKSB0aHJvdyBlcnIKICAgICAgICAgICAgICAgICAgICBpZiAob3JkZXIgPT0gImFzY2VuZGluZyIpIGh1bWlkaXR5ID0gKHBhcnNlSW50KGh1bWlkaXR5KSsyKS50b1N0cmluZygpOwogICAgICAgICAgICAgICAgICAgIGlmIChvcmRlciA9PSAiZGVzY2VuZGluZyIpIGh1bWlkaXR5ID0gKHBhcnNlSW50KGh1bWlkaXR5KS0yKS50b1N0cmluZygpOwogICAgICAgICAgICAgICAgICAgIGlmIChwYXJzZUludChodW1pZGl0eSkgPD0gMzApIGNsaWVudFJlZGlzLnNldCgib3JkZXIiLCAiYXNjZW5kaW5nIik7CiAgICAgICAgICAgICAgICAgICAgICAgIGNsaWVudFJlZGlzLnNldCgiaHVtaWRpdHkiLCBodW1pZGl0eSk7CgogICAgICAgICAgICAgICAgICAgICAgICBjbGllbnQucHVibGlzaCgiaW90L3NlbnNvcnMvaHVtaWRpdHkiLCBodW1pZGl0eSwgZnVuY3Rpb24gKCkgewogICAgICAgICAgICAgICAgICAgICAgICAgICAgY2xpZW50LmVuZCgpOwogICAgICAgICAgICAgICAgICAgICAgICAgICAgY29udGV4dC5jYWxsYmFjaygiU2VudCAiICsgaHVtaWRpdHkpOwogICAgICAgICAgICAgICAgICAgICAgICB9KTsKICAgICAgICAgICAgICB9KQogICAgICAgICAgfQogICAgICB9KTsKCiAgICB9KTsKICB9Owo=
    commands:
      - 'npm install mqtt'
      - 'npm install redis'
    codeEntryType: sourceCode
  platform: {}